export enum usersTypes {
    FETCH_USERS_LIST = 'FETCH_USERS_LIST',
    SET_USERS_LIST = 'SET_USERS_LIST',
    ERROR_FETCH_USERS_LIST = 'ERROR_FETCH_USERS_LIST',

    FETCH_POSTS = 'FETCH_POSTS',
    SET_POSTS = 'SET_POSTS'
}
